/* automatically generated by rust-bindgen */

#![allow(dead_code,
         non_camel_case_types,
         non_upper_case_globals,
         non_snake_case)]
pub enum wkhtmltoimage_global_settings { }
pub enum wkhtmltoimage_converter { }
pub type wkhtmltoimage_str_callback =
    ::std::option::Option<unsafe extern "C" fn(converter:
                                                   *mut wkhtmltoimage_converter,
                                               str:
                                                   *const ::std::os::raw::c_char)>;
pub type wkhtmltoimage_int_callback =
    ::std::option::Option<unsafe extern "C" fn(converter:
                                                   *mut wkhtmltoimage_converter,
                                               val: ::std::os::raw::c_int)>;
pub type wkhtmltoimage_void_callback =
    ::std::option::Option<unsafe extern "C" fn(converter:
                                                   *mut wkhtmltoimage_converter)>;
#[link(name = "wkhtmltox", kind = "dylib")]
extern "C" {
    pub fn wkhtmltoimage_init(use_graphics: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn wkhtmltoimage_deinit() -> ::std::os::raw::c_int;
    pub fn wkhtmltoimage_extended_qt() -> ::std::os::raw::c_int;
    pub fn wkhtmltoimage_version() -> *const ::std::os::raw::c_char;
    pub fn wkhtmltoimage_create_global_settings()
     -> *mut wkhtmltoimage_global_settings;
    pub fn wkhtmltoimage_set_global_setting(settings:
                                                *mut wkhtmltoimage_global_settings,
                                            name:
                                                *const ::std::os::raw::c_char,
                                            value:
                                                *const ::std::os::raw::c_char)
     -> ::std::os::raw::c_int;
    pub fn wkhtmltoimage_get_global_setting(settings:
                                                *mut wkhtmltoimage_global_settings,
                                            name:
                                                *const ::std::os::raw::c_char,
                                            value:
                                                *mut ::std::os::raw::c_char,
                                            vs: ::std::os::raw::c_int)
     -> ::std::os::raw::c_int;
    pub fn wkhtmltoimage_create_converter(settings:
                                              *mut wkhtmltoimage_global_settings,
                                          data: *const ::std::os::raw::c_char)
     -> *mut wkhtmltoimage_converter;
    pub fn wkhtmltoimage_destroy_converter(converter:
                                               *mut wkhtmltoimage_converter);
    pub fn wkhtmltoimage_set_warning_callback(converter:
                                                  *mut wkhtmltoimage_converter,
                                              cb: wkhtmltoimage_str_callback);
    pub fn wkhtmltoimage_set_error_callback(converter:
                                                *mut wkhtmltoimage_converter,
                                            cb: wkhtmltoimage_str_callback);
    pub fn wkhtmltoimage_set_phase_changed_callback(converter:
                                                        *mut wkhtmltoimage_converter,
                                                    cb:
                                                        wkhtmltoimage_void_callback);
    pub fn wkhtmltoimage_set_progress_changed_callback(converter:
                                                           *mut wkhtmltoimage_converter,
                                                       cb:
                                                           wkhtmltoimage_int_callback);
    pub fn wkhtmltoimage_set_finished_callback(converter:
                                                   *mut wkhtmltoimage_converter,
                                               cb:
                                                   wkhtmltoimage_int_callback);
    pub fn wkhtmltoimage_convert(converter: *mut wkhtmltoimage_converter)
     -> ::std::os::raw::c_int;
    pub fn wkhtmltoimage_current_phase(converter:
                                           *mut wkhtmltoimage_converter)
     -> ::std::os::raw::c_int;
    pub fn wkhtmltoimage_phase_count(converter: *mut wkhtmltoimage_converter)
     -> ::std::os::raw::c_int;
    pub fn wkhtmltoimage_phase_description(converter:
                                               *mut wkhtmltoimage_converter,
                                           phase: ::std::os::raw::c_int)
     -> *const ::std::os::raw::c_char;
    pub fn wkhtmltoimage_progress_string(converter:
                                             *mut wkhtmltoimage_converter)
     -> *const ::std::os::raw::c_char;
    pub fn wkhtmltoimage_http_error_code(converter:
                                             *mut wkhtmltoimage_converter)
     -> ::std::os::raw::c_int;
    pub fn wkhtmltoimage_get_output(converter: *mut wkhtmltoimage_converter,
                                    arg1: *mut *const ::std::os::raw::c_uchar)
     -> ::std::os::raw::c_long;
}
