/* automatically generated by rust-bindgen 0.57.0 */

#![allow(non_camel_case_types)]

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wkhtmltopdf_global_settings {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wkhtmltopdf_object_settings {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct wkhtmltopdf_converter {
    _unused: [u8; 0],
}
pub type wkhtmltopdf_str_callback = ::std::option::Option<
    unsafe extern "C" fn(
        converter: *mut wkhtmltopdf_converter,
        str_: *const ::std::os::raw::c_char,
    ),
>;
pub type wkhtmltopdf_int_callback = ::std::option::Option<
    unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter, val: ::std::os::raw::c_int),
>;
pub type wkhtmltopdf_void_callback =
    ::std::option::Option<unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter)>;
extern crate libloading;
pub struct wkhtmltox {
    __library: libloading::Library,
    pub wkhtmltopdf_init: Result<
        unsafe extern "C" fn(use_graphics: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
        libloading::Error,
    >,
    pub wkhtmltopdf_deinit:
        Result<unsafe extern "C" fn() -> ::std::os::raw::c_int, libloading::Error>,
    pub wkhtmltopdf_extended_qt:
        Result<unsafe extern "C" fn() -> ::std::os::raw::c_int, libloading::Error>,
    pub wkhtmltopdf_version:
        Result<unsafe extern "C" fn() -> *const ::std::os::raw::c_char, libloading::Error>,
    pub wkhtmltopdf_create_global_settings:
        Result<unsafe extern "C" fn() -> *mut wkhtmltopdf_global_settings, libloading::Error>,
    pub wkhtmltopdf_destroy_global_settings:
        Result<unsafe extern "C" fn(arg1: *mut wkhtmltopdf_global_settings), libloading::Error>,
    pub wkhtmltopdf_create_object_settings:
        Result<unsafe extern "C" fn() -> *mut wkhtmltopdf_object_settings, libloading::Error>,
    pub wkhtmltopdf_destroy_object_settings:
        Result<unsafe extern "C" fn(arg1: *mut wkhtmltopdf_object_settings), libloading::Error>,
    pub wkhtmltopdf_set_global_setting: Result<
        unsafe extern "C" fn(
            settings: *mut wkhtmltopdf_global_settings,
            name: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
        libloading::Error,
    >,
    pub wkhtmltopdf_get_global_setting: Result<
        unsafe extern "C" fn(
            settings: *mut wkhtmltopdf_global_settings,
            name: *const ::std::os::raw::c_char,
            value: *mut ::std::os::raw::c_char,
            vs: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
        libloading::Error,
    >,
    pub wkhtmltopdf_set_object_setting: Result<
        unsafe extern "C" fn(
            settings: *mut wkhtmltopdf_object_settings,
            name: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
        libloading::Error,
    >,
    pub wkhtmltopdf_get_object_setting: Result<
        unsafe extern "C" fn(
            settings: *mut wkhtmltopdf_object_settings,
            name: *const ::std::os::raw::c_char,
            value: *mut ::std::os::raw::c_char,
            vs: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
        libloading::Error,
    >,
    pub wkhtmltopdf_create_converter: Result<
        unsafe extern "C" fn(
            settings: *mut wkhtmltopdf_global_settings,
        ) -> *mut wkhtmltopdf_converter,
        libloading::Error,
    >,
    pub wkhtmltopdf_destroy_converter:
        Result<unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter), libloading::Error>,
    pub wkhtmltopdf_set_debug_callback: Result<
        unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter, cb: wkhtmltopdf_str_callback),
        libloading::Error,
    >,
    pub wkhtmltopdf_set_info_callback: Result<
        unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter, cb: wkhtmltopdf_str_callback),
        libloading::Error,
    >,
    pub wkhtmltopdf_set_warning_callback: Result<
        unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter, cb: wkhtmltopdf_str_callback),
        libloading::Error,
    >,
    pub wkhtmltopdf_set_error_callback: Result<
        unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter, cb: wkhtmltopdf_str_callback),
        libloading::Error,
    >,
    pub wkhtmltopdf_set_phase_changed_callback: Result<
        unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter, cb: wkhtmltopdf_void_callback),
        libloading::Error,
    >,
    pub wkhtmltopdf_set_progress_changed_callback: Result<
        unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter, cb: wkhtmltopdf_int_callback),
        libloading::Error,
    >,
    pub wkhtmltopdf_set_finished_callback: Result<
        unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter, cb: wkhtmltopdf_int_callback),
        libloading::Error,
    >,
    pub wkhtmltopdf_convert: Result<
        unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter) -> ::std::os::raw::c_int,
        libloading::Error,
    >,
    pub wkhtmltopdf_add_object: Result<
        unsafe extern "C" fn(
            converter: *mut wkhtmltopdf_converter,
            setting: *mut wkhtmltopdf_object_settings,
            data: *const ::std::os::raw::c_char,
        ),
        libloading::Error,
    >,
    pub wkhtmltopdf_current_phase: Result<
        unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter) -> ::std::os::raw::c_int,
        libloading::Error,
    >,
    pub wkhtmltopdf_phase_count: Result<
        unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter) -> ::std::os::raw::c_int,
        libloading::Error,
    >,
    pub wkhtmltopdf_phase_description: Result<
        unsafe extern "C" fn(
            converter: *mut wkhtmltopdf_converter,
            phase: ::std::os::raw::c_int,
        ) -> *const ::std::os::raw::c_char,
        libloading::Error,
    >,
    pub wkhtmltopdf_progress_string: Result<
        unsafe extern "C" fn(
            converter: *mut wkhtmltopdf_converter,
        ) -> *const ::std::os::raw::c_char,
        libloading::Error,
    >,
    pub wkhtmltopdf_http_error_code: Result<
        unsafe extern "C" fn(converter: *mut wkhtmltopdf_converter) -> ::std::os::raw::c_int,
        libloading::Error,
    >,
    pub wkhtmltopdf_get_output: Result<
        unsafe extern "C" fn(
            converter: *mut wkhtmltopdf_converter,
            arg1: *mut *const ::std::os::raw::c_uchar,
        ) -> ::std::os::raw::c_long,
        libloading::Error,
    >,
}
impl wkhtmltox {
    pub unsafe fn new<P>(path: P) -> Result<Self, libloading::Error>
    where
        P: AsRef<::std::ffi::OsStr>,
    {
        let __library = libloading::Library::new(path)?;
        let wkhtmltopdf_init = __library.get(b"wkhtmltopdf_init\0").map(|sym| *sym);
        let wkhtmltopdf_deinit = __library.get(b"wkhtmltopdf_deinit\0").map(|sym| *sym);
        let wkhtmltopdf_extended_qt = __library.get(b"wkhtmltopdf_extended_qt\0").map(|sym| *sym);
        let wkhtmltopdf_version = __library.get(b"wkhtmltopdf_version\0").map(|sym| *sym);
        let wkhtmltopdf_create_global_settings = __library
            .get(b"wkhtmltopdf_create_global_settings\0")
            .map(|sym| *sym);
        let wkhtmltopdf_destroy_global_settings = __library
            .get(b"wkhtmltopdf_destroy_global_settings\0")
            .map(|sym| *sym);
        let wkhtmltopdf_create_object_settings = __library
            .get(b"wkhtmltopdf_create_object_settings\0")
            .map(|sym| *sym);
        let wkhtmltopdf_destroy_object_settings = __library
            .get(b"wkhtmltopdf_destroy_object_settings\0")
            .map(|sym| *sym);
        let wkhtmltopdf_set_global_setting = __library
            .get(b"wkhtmltopdf_set_global_setting\0")
            .map(|sym| *sym);
        let wkhtmltopdf_get_global_setting = __library
            .get(b"wkhtmltopdf_get_global_setting\0")
            .map(|sym| *sym);
        let wkhtmltopdf_set_object_setting = __library
            .get(b"wkhtmltopdf_set_object_setting\0")
            .map(|sym| *sym);
        let wkhtmltopdf_get_object_setting = __library
            .get(b"wkhtmltopdf_get_object_setting\0")
            .map(|sym| *sym);
        let wkhtmltopdf_create_converter = __library
            .get(b"wkhtmltopdf_create_converter\0")
            .map(|sym| *sym);
        let wkhtmltopdf_destroy_converter = __library
            .get(b"wkhtmltopdf_destroy_converter\0")
            .map(|sym| *sym);
        let wkhtmltopdf_set_debug_callback = __library
            .get(b"wkhtmltopdf_set_debug_callback\0")
            .map(|sym| *sym);
        let wkhtmltopdf_set_info_callback = __library
            .get(b"wkhtmltopdf_set_info_callback\0")
            .map(|sym| *sym);
        let wkhtmltopdf_set_warning_callback = __library
            .get(b"wkhtmltopdf_set_warning_callback\0")
            .map(|sym| *sym);
        let wkhtmltopdf_set_error_callback = __library
            .get(b"wkhtmltopdf_set_error_callback\0")
            .map(|sym| *sym);
        let wkhtmltopdf_set_phase_changed_callback = __library
            .get(b"wkhtmltopdf_set_phase_changed_callback\0")
            .map(|sym| *sym);
        let wkhtmltopdf_set_progress_changed_callback = __library
            .get(b"wkhtmltopdf_set_progress_changed_callback\0")
            .map(|sym| *sym);
        let wkhtmltopdf_set_finished_callback = __library
            .get(b"wkhtmltopdf_set_finished_callback\0")
            .map(|sym| *sym);
        let wkhtmltopdf_convert = __library.get(b"wkhtmltopdf_convert\0").map(|sym| *sym);
        let wkhtmltopdf_add_object = __library.get(b"wkhtmltopdf_add_object\0").map(|sym| *sym);
        let wkhtmltopdf_current_phase = __library
            .get(b"wkhtmltopdf_current_phase\0")
            .map(|sym| *sym);
        let wkhtmltopdf_phase_count = __library.get(b"wkhtmltopdf_phase_count\0").map(|sym| *sym);
        let wkhtmltopdf_phase_description = __library
            .get(b"wkhtmltopdf_phase_description\0")
            .map(|sym| *sym);
        let wkhtmltopdf_progress_string = __library
            .get(b"wkhtmltopdf_progress_string\0")
            .map(|sym| *sym);
        let wkhtmltopdf_http_error_code = __library
            .get(b"wkhtmltopdf_http_error_code\0")
            .map(|sym| *sym);
        let wkhtmltopdf_get_output = __library.get(b"wkhtmltopdf_get_output\0").map(|sym| *sym);
        Ok(wkhtmltox {
            __library,
            wkhtmltopdf_init,
            wkhtmltopdf_deinit,
            wkhtmltopdf_extended_qt,
            wkhtmltopdf_version,
            wkhtmltopdf_create_global_settings,
            wkhtmltopdf_destroy_global_settings,
            wkhtmltopdf_create_object_settings,
            wkhtmltopdf_destroy_object_settings,
            wkhtmltopdf_set_global_setting,
            wkhtmltopdf_get_global_setting,
            wkhtmltopdf_set_object_setting,
            wkhtmltopdf_get_object_setting,
            wkhtmltopdf_create_converter,
            wkhtmltopdf_destroy_converter,
            wkhtmltopdf_set_debug_callback,
            wkhtmltopdf_set_info_callback,
            wkhtmltopdf_set_warning_callback,
            wkhtmltopdf_set_error_callback,
            wkhtmltopdf_set_phase_changed_callback,
            wkhtmltopdf_set_progress_changed_callback,
            wkhtmltopdf_set_finished_callback,
            wkhtmltopdf_convert,
            wkhtmltopdf_add_object,
            wkhtmltopdf_current_phase,
            wkhtmltopdf_phase_count,
            wkhtmltopdf_phase_description,
            wkhtmltopdf_progress_string,
            wkhtmltopdf_http_error_code,
            wkhtmltopdf_get_output,
        })
    }
    pub unsafe fn wkhtmltopdf_init(
        &self,
        use_graphics: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int {
        let sym = self
            .wkhtmltopdf_init
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(use_graphics)
    }
    pub unsafe fn wkhtmltopdf_deinit(&self) -> ::std::os::raw::c_int {
        let sym = self
            .wkhtmltopdf_deinit
            .as_ref()
            .expect("Expected function, got error.");
        (sym)()
    }
    pub unsafe fn wkhtmltopdf_extended_qt(&self) -> ::std::os::raw::c_int {
        let sym = self
            .wkhtmltopdf_extended_qt
            .as_ref()
            .expect("Expected function, got error.");
        (sym)()
    }
    pub unsafe fn wkhtmltopdf_version(&self) -> *const ::std::os::raw::c_char {
        let sym = self
            .wkhtmltopdf_version
            .as_ref()
            .expect("Expected function, got error.");
        (sym)()
    }
    pub unsafe fn wkhtmltopdf_create_global_settings(&self) -> *mut wkhtmltopdf_global_settings {
        let sym = self
            .wkhtmltopdf_create_global_settings
            .as_ref()
            .expect("Expected function, got error.");
        (sym)()
    }
    pub unsafe fn wkhtmltopdf_destroy_global_settings(
        &self,
        arg1: *mut wkhtmltopdf_global_settings,
    ) -> () {
        let sym = self
            .wkhtmltopdf_destroy_global_settings
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(arg1)
    }
    pub unsafe fn wkhtmltopdf_create_object_settings(&self) -> *mut wkhtmltopdf_object_settings {
        let sym = self
            .wkhtmltopdf_create_object_settings
            .as_ref()
            .expect("Expected function, got error.");
        (sym)()
    }
    pub unsafe fn wkhtmltopdf_destroy_object_settings(
        &self,
        arg1: *mut wkhtmltopdf_object_settings,
    ) -> () {
        let sym = self
            .wkhtmltopdf_destroy_object_settings
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(arg1)
    }
    pub unsafe fn wkhtmltopdf_set_global_setting(
        &self,
        settings: *mut wkhtmltopdf_global_settings,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        let sym = self
            .wkhtmltopdf_set_global_setting
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(settings, name, value)
    }
    pub unsafe fn wkhtmltopdf_get_global_setting(
        &self,
        settings: *mut wkhtmltopdf_global_settings,
        name: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_char,
        vs: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int {
        let sym = self
            .wkhtmltopdf_get_global_setting
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(settings, name, value, vs)
    }
    pub unsafe fn wkhtmltopdf_set_object_setting(
        &self,
        settings: *mut wkhtmltopdf_object_settings,
        name: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int {
        let sym = self
            .wkhtmltopdf_set_object_setting
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(settings, name, value)
    }
    pub unsafe fn wkhtmltopdf_get_object_setting(
        &self,
        settings: *mut wkhtmltopdf_object_settings,
        name: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_char,
        vs: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int {
        let sym = self
            .wkhtmltopdf_get_object_setting
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(settings, name, value, vs)
    }
    pub unsafe fn wkhtmltopdf_create_converter(
        &self,
        settings: *mut wkhtmltopdf_global_settings,
    ) -> *mut wkhtmltopdf_converter {
        let sym = self
            .wkhtmltopdf_create_converter
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(settings)
    }
    pub unsafe fn wkhtmltopdf_destroy_converter(
        &self,
        converter: *mut wkhtmltopdf_converter,
    ) -> () {
        let sym = self
            .wkhtmltopdf_destroy_converter
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter)
    }
    pub unsafe fn wkhtmltopdf_set_debug_callback(
        &self,
        converter: *mut wkhtmltopdf_converter,
        cb: wkhtmltopdf_str_callback,
    ) -> () {
        let sym = self
            .wkhtmltopdf_set_debug_callback
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter, cb)
    }
    pub unsafe fn wkhtmltopdf_set_info_callback(
        &self,
        converter: *mut wkhtmltopdf_converter,
        cb: wkhtmltopdf_str_callback,
    ) -> () {
        let sym = self
            .wkhtmltopdf_set_info_callback
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter, cb)
    }
    pub unsafe fn wkhtmltopdf_set_warning_callback(
        &self,
        converter: *mut wkhtmltopdf_converter,
        cb: wkhtmltopdf_str_callback,
    ) -> () {
        let sym = self
            .wkhtmltopdf_set_warning_callback
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter, cb)
    }
    pub unsafe fn wkhtmltopdf_set_error_callback(
        &self,
        converter: *mut wkhtmltopdf_converter,
        cb: wkhtmltopdf_str_callback,
    ) -> () {
        let sym = self
            .wkhtmltopdf_set_error_callback
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter, cb)
    }
    pub unsafe fn wkhtmltopdf_set_phase_changed_callback(
        &self,
        converter: *mut wkhtmltopdf_converter,
        cb: wkhtmltopdf_void_callback,
    ) -> () {
        let sym = self
            .wkhtmltopdf_set_phase_changed_callback
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter, cb)
    }
    pub unsafe fn wkhtmltopdf_set_progress_changed_callback(
        &self,
        converter: *mut wkhtmltopdf_converter,
        cb: wkhtmltopdf_int_callback,
    ) -> () {
        let sym = self
            .wkhtmltopdf_set_progress_changed_callback
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter, cb)
    }
    pub unsafe fn wkhtmltopdf_set_finished_callback(
        &self,
        converter: *mut wkhtmltopdf_converter,
        cb: wkhtmltopdf_int_callback,
    ) -> () {
        let sym = self
            .wkhtmltopdf_set_finished_callback
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter, cb)
    }
    pub unsafe fn wkhtmltopdf_convert(
        &self,
        converter: *mut wkhtmltopdf_converter,
    ) -> ::std::os::raw::c_int {
        let sym = self
            .wkhtmltopdf_convert
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter)
    }
    pub unsafe fn wkhtmltopdf_add_object(
        &self,
        converter: *mut wkhtmltopdf_converter,
        setting: *mut wkhtmltopdf_object_settings,
        data: *const ::std::os::raw::c_char,
    ) -> () {
        let sym = self
            .wkhtmltopdf_add_object
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter, setting, data)
    }
    pub unsafe fn wkhtmltopdf_current_phase(
        &self,
        converter: *mut wkhtmltopdf_converter,
    ) -> ::std::os::raw::c_int {
        let sym = self
            .wkhtmltopdf_current_phase
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter)
    }
    pub unsafe fn wkhtmltopdf_phase_count(
        &self,
        converter: *mut wkhtmltopdf_converter,
    ) -> ::std::os::raw::c_int {
        let sym = self
            .wkhtmltopdf_phase_count
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter)
    }
    pub unsafe fn wkhtmltopdf_phase_description(
        &self,
        converter: *mut wkhtmltopdf_converter,
        phase: ::std::os::raw::c_int,
    ) -> *const ::std::os::raw::c_char {
        let sym = self
            .wkhtmltopdf_phase_description
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter, phase)
    }
    pub unsafe fn wkhtmltopdf_progress_string(
        &self,
        converter: *mut wkhtmltopdf_converter,
    ) -> *const ::std::os::raw::c_char {
        let sym = self
            .wkhtmltopdf_progress_string
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter)
    }
    pub unsafe fn wkhtmltopdf_http_error_code(
        &self,
        converter: *mut wkhtmltopdf_converter,
    ) -> ::std::os::raw::c_int {
        let sym = self
            .wkhtmltopdf_http_error_code
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter)
    }
    pub unsafe fn wkhtmltopdf_get_output(
        &self,
        converter: *mut wkhtmltopdf_converter,
        arg1: *mut *const ::std::os::raw::c_uchar,
    ) -> ::std::os::raw::c_long {
        let sym = self
            .wkhtmltopdf_get_output
            .as_ref()
            .expect("Expected function, got error.");
        (sym)(converter, arg1)
    }
}
